%%  ABCD(PN) grid deformation
addpath('tests');
warning off
clear all 
close all 
in_mesh       =  './data/bar100x100sub.obj';
target_mesh   =  './data/bar100x100sub_noisy.obj';
tmesh_file    =  './data/tmesh_bar100x100sub.mat';
load('./data/visualization_params.mat');
load('./data/general_params.mat');
optParamList = {...
    OptimizationParams(OptimizationParams.ParseOptions(...
          'LS_iter',100,'dist_name','FS','dist_draw','FS','cycle_num',4,...
          'solver','GD','LS_interval',1.05,'penalize_flips',0,'Lambda',0,...
          'block_max_iter',[1 10 0.5])...
    ),...
    OptimizationParams(OptimizationParams.ParseOptions('LS_iter',50,'LS_interval',0.5,'LS_bt_step',0.8,...
          'project_kernel',1,'dist_name','SymDirSigned2D','dist_draw','SymDir2D','cycle_num',4,'local_global_policy',4,...
          'solver','PN','block_max_iter',[1 4 0.5])...  
    )...
};

options.iter_num =20;
options.free_bnd =1;
run ABCD_wrapper_script_2D.m

%% ABCD(PN) elephant with random interior
addpath('tests');
clear all
close all

in_mesh    =  './data/elephant30K_s.obj';
tmesh_file = './data/elephant30K_t.mat';
target_mesh = './data/tmesh_of_elephant_30K.mat';

load('./data/visualization_params.mat');
load('./data/general_params.mat');

optParamList = {...
    OptimizationParams(OptimizationParams.ParseOptions(...
    'LS_iter',50,'dist_name','FS','cycle_num',4,...
    'solver','GD','LS_interval',2,'penalize_flips',0,'Lambda',[0 0],...
    'block_max_iter',[1 5])...
    ),...
    OptimizationParams(OptimizationParams.ParseOptions(...
    'LS_iter',50,'LS_interval',0.5,...
    'dist_name','SymDirSigned2D','cycle_num',4,...
    'solver','PN','block_max_iter',[1 2])...  %new line
    )...
    };

options.free_bnd =0;
options.iter_num =30;
run ABCD_wrapper_script_2D.m

disp([newline '=== Solving the same problem with different ABCD parameters ===']);
optParamList = {...
    OptimizationParams(OptimizationParams.ParseOptions(...
    'LS_iter',50,'dist_name','FS','cycle_num',2,...
    'solver','GD','LS_interval',2,'penalize_flips',0,'Lambda',[0 0],...
    'block_max_iter',[1 10 0.5])...
    ),...
    OptimizationParams(OptimizationParams.ParseOptions(...
    'LS_iter',50,'LS_interval',0.5,'LS_bt_step',0.8,...
    'dist_name','SymDirSigned2D','cycle_num',2,...
    'solver','PN','block_max_iter',[1 4 0.5])...  %new line
    )...
    };

options.free_bnd =0;
options.iter_num =30;
run ABCD_wrapper_script_2D.m

%% ABCD(PN) elephant high resolution with random interior
close all
clear all
in_mesh       =  './data/elephant120K_s.obj';
target_mesh   =  './data/elephant120K_t_1.mat';
tmesh_file    = './data/tmesh_of_elephant_120K.mat';

load('./data/visualization_params.mat');
load('./data/general_params.mat');
optParamList = {...
        OptimizationParams(OptimizationParams.ParseOptions(...
        'LS_iter',50,'dist_name','FS','cycle_num',4,...
        'solver','GD','LS_interval',2,'penalize_flips',0,'Lambda',[0 0],'LS_alpha',10^-5,...
        'block_max_iter',[1 10 0.5])...
        ),...
        OptimizationParams(OptimizationParams.ParseOptions('LS_iter',50,'LS_interval',0.5,'LS_bt_step',0.8,...
        'project_kernel',1,'dist_name','SymDirSigned2D','cycle_num',2,...
        'solver','PN','block_max_iter',[1 2])...  
        )...
};
options.iter_num =35;
options.free_bnd =0;
run ABCD_wrapper_script_2D.m
%% ABCD(PN) octopus constrained parametrization
%clear all 
close all 

in_mesh       =  './data/octopus_s.obj'; 
target_mesh   =  './data/octopus_t_1.mat';
tmesh_file   =  './data/tmesh_of_octopus.mat';

load('./data/visualization_params.mat');
load('./data/general_params.mat');
movieOpt.mark_fixed_vertices=1;
options.is_uv_mesh=1;

optParamList = {...
        OptimizationParams(OptimizationParams.ParseOptions(...
        'LS_iter',100,'dist_name','FS','cycle_num',4,...
        'solver','GD','LS_interval',1.05,'penalize_flips',0,'Lambda',[0 0],'LS_alpha',10^-5,...
        'block_max_iter',[1 10 0.5])...
        ),...
        OptimizationParams(OptimizationParams.ParseOptions('LS_iter',100,'LS_interval',0.5,...
        'dist_name','SymDirSigned2D','cycle_num',4,...
        'solver','PN','block_max_iter',[1 4 0.5])...  
        )...
};
options.iter_num =35;
options.free_bnd =1;
tic
run ABCD_wrapper_script_2D.m
toc
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp('%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%');
disp('Visualizing  results for each iteration (slower performance)');
disp('%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%');
%%  ABCD(PN) grid deformation
addpath('tests');
clear all 
close all 
in_mesh       =  './data/bar100x100sub.obj';
target_mesh   =  './data/bar100x100sub_noisy.obj';
tmesh_file    =  './data/tmesh_bar100x100sub.mat';

load('./data/visualization_params.mat');
load('./data/general_params.mat');

%energy/solver/termination-criteria specifications 
optParamList = {...
    OptimizationParams(OptimizationParams.ParseOptions(...
          'LS_iter',100,'dist_name','FS','dist_draw','FS','cycle_num',4,...
          'solver','GD','LS_interval',1.05,'penalize_flips',0,'Lambda',0,...
          'block_max_iter',[1 10])...
    ),...
    OptimizationParams(OptimizationParams.ParseOptions('LS_iter',50,'LS_interval',0.5,'LS_bt_step',0.8,...
          'project_kernel',1,'dist_name','SymDirSigned2D','dist_draw','SymDir2D','cycle_num',4,'local_global_policy',4,...
          'solver','PN','block_max_iter',[1 4])...  
    )...
};

options.fig_name= './reports/grid_deformation';
options.iter_num =20;
options.dist_name = 'SymDirSigned2D';
options.dist_draw = 'SymDirSigned2D';
options.free_bnd =1;
options.visualize_iterations =1;
run ABCD_wrapper_script_2D.m
%% ABCD(PN) elephant with random interior
clear all 
close all 
ENABLE_DRAWING=1; 
in_mesh       =  './data/elephant120K_s.obj';
target_mesh   =  './data/elephant120K_t_1.mat';
tmesh_file    = './data/tmesh_of_elephant_120K.mat';

load('./data/visualization_params.mat');
load('./data/general_params.mat');
%energy/solver/termination-criteria specifications 
optParamList = {...
        OptimizationParams(OptimizationParams.ParseOptions(...
        'LS_iter',1000,'dist_name','FS','dist_draw','FS','cycle_num',4,...
        'solver','GD','LS_interval',2,'penalize_flips',0,'Lambda',[0 0],'LS_alpha',10^-5,...
        'block_max_iter',[1 10])...
        ),...
        OptimizationParams(OptimizationParams.ParseOptions('LS_iter',500,'LS_interval',0.5,'LS_bt_step',0.8,...
        'project_kernel',1,'dist_name','SymDirSigned2D','dist_draw','SymDir2D','cycle_num',4,...
        'solver','PN','block_max_iter',[1 2])...  
        )...
};

options.fig_name= './reports/elephant_high';
options.iter_num =35;
options.dist_name = 'SymDirSigned2D';
options.dist_draw = 'SymDirSigned2D';
options.free_bnd =0;
options.visualize_iterations =1;
run ABCD_wrapper_script_2D.m
%% ABCD(PN) octopus constrained parametrization
clear all 
close all 

in_mesh       =  './data/octopus_s.obj'; 
target_mesh   =  './data/octopus_t_1.mat';
tmesh_file   =  './data/tmesh_of_octopus.mat';

load('./data/visualization_params.mat');
load('./data/general_params.mat');
movieOpt.mark_fixed_vertices=1;
options.is_uv_mesh=1;

optParamList = {...
        OptimizationParams(OptimizationParams.ParseOptions(...
        'LS_iter',100,'dist_name','FS','dist_draw','FS','cycle_num',4,...
        'solver','GD','LS_interval',1.05,'penalize_flips',0,'Lambda',[0 0],'LS_alpha',10^-5,...
        'block_max_iter',[1 10])...
        ),...
        OptimizationParams(OptimizationParams.ParseOptions('LS_iter',100,'LS_interval',0.5,...
        'dist_name','SymDirSigned2D','dist_draw','SymDir2D','cycle_num',4,...
        'solver','PN','block_max_iter',[1 4])...  
        )...
};
options.fig_name= './reports/octopus';
options.iter_num =30;
options.dist_name = 'SymDirSigned2D';
options.dist_draw = 'SymDirSigned2D';
options.free_bnd =1;
options.visualize_iterations =1;
run ABCD_wrapper_script_2D.m