%% Run from "mexed_solver/mex" folder !
% setting compiler mex options 
clear mex
eigen_path = 'C:/Users/Administrator/MEGA/Phd general/ABCD-master/C++external/eigen/'; %<--Set
igl_path =   'C:/Users/Administrator/MEGA/Phd general/ABCD-master/C++external/libigl/include';%<--Set;
boost_path = 'C:/Users/Administrator/MEGA/Phd general/ABCD-master/C++external';%<--Set
inc_path = './cpp/';
VS_path = '../VS_mex/simple_mex';%for compiling from Visual Studio 


inc_path = './cpp/';
VS_path = '../VS_mex/simple_mex';
compiler_option='/openmp';
%% 
clear mex
mex(['-I',eigen_path], ['-I',inc_path], ['-I',igl_path], 'load_obj_mesh_mex.cc', 'cpp/common/util/mesh_obj_io.cc');

%%  compile 2D ABCD code with Eigen 
mex( '-DMEX_COMPILE_FLAG',['COMPFLAGS="$COMPFLAGS ' compiler_option '"'],['-I',eigen_path],['-I',boost_path],...
        ['-I',inc_path],['-I',VS_path],'ABCD_optimize_single_measure_mex.cc', ...
        ['-I',VS_path],'ABCD_optimization_core.cpp', ...
        'cpp/energy_model/mesh_distortion/isotropic_svd_energy_model_2d.cc', ...
        'cpp/energy_model/mesh_distortion/isotropic_svd_energy_model_3d.cc', ...
        'cpp/energy_model/distortion_kernel/arap_kernel_2d.cc', ...
        'cpp/energy_model/distortion_kernel/flip_penalty_kernel_2d.cc',...
        'cpp/energy_model/distortion_kernel/symmetric_dirichlet_kernel_2d.cc',....
        'cpp/energy_model/distortion_kernel/sym_dirichlet_filtered_kernel_2d.cc',....
        'cpp/common/util/linalg_util.cc', 'cpp/common/solver/eigen/eigen_solver.cc', ...
        'cpp/common/optimization/line_search_util.cc', 'cpp/common/optimization/stop_check_util.cc',...
        'cpp/data_io/data_io_utils.cpp','cpp/common/util/graph_util.cpp');


%%  compile 3D code
mex( '-DMEX_COMPILE_FLAG',['COMPFLAGS="$COMPFLAGS ' compiler_option '"'],['-I',eigen_path], ['-I',inc_path],['-I',VS_path],['-I',boost_path],...
        'compute_optimal_solution_BCD_parallel_3d_mex.cc', ...
        'cpp/energy_model/mesh_distortion/isotropic_svd_energy_model_2d.cc', ...
        'cpp/energy_model/mesh_distortion/isotropic_svd_energy_model_3d.cc', ...
        'cpp/energy_model/distortion_kernel/arap_kernel_3d.cc', ...
        'cpp/energy_model/distortion_kernel/symmetric_dirichlet_kernel_3d.cc',....
        'cpp/common/util/linalg_util.cc', 'cpp/common/solver/eigen/eigen_solver.cc', ...
        'cpp/common/optimization/line_search_util.cc', 'cpp/common/optimization/stop_check_util.cc',...
        'cpp/data_io/data_io_utils.cpp','cpp/common/util/graph_util.cpp');

