%%  Copyright @2020. All rights reserved.
%   Authors:  anaitsat@campus.technion.ac.il  (Alexander Naitsat)

%% Run from "mexed_solver/mex" folder!
clear mex
% Dependencies:
eigen_path = './../../dependencies/eigen/';          %<--Set
igl_path =   './../../dependencies/libigl/include';  %<--Set
boost_path = './../../dependencies';                 %<--Set

inc_path = './cpp/';              %
VS_path = '../VS_mex/simple_mex'; % For compiling from Visual Studio
compiler_option='/openmp';        % Compiler flags
compile_with_pardiso =0;          %<-- Select Eigen/Pardiso linear solver
% For Pardiso version:
% 1.  Set "#define _USE_PARDISO 1" in  linear_solver.h
% 2.  Put pardiso binaries in /mexed_solver/mex/, and link it with  mex
%% data load 
clear mex
mex(['-I',eigen_path], ['-I',inc_path], ['-I',igl_path], 'load_obj_mesh_mex.cc', 'cpp/common/util/mesh_obj_io.cc');

%% Mesh Data initialization and distortion computation code
% Do not set _USE_PARDISO macro in linear_solver.h while compiling GetMeshData_mex
mex( '-DMEX_COMPILE_FLAG',['COMPFLAGS="$COMPFLAGS ' compiler_option '"'],['-I',eigen_path],['-I',boost_path],...
    ['-I',inc_path],['-I',VS_path],'GetMeshData_mex.cc', ...
    'cpp/energy_model/mesh_distortion/isotropic_svd_energy_model_2d.cc', ...
    'cpp/energy_model/mesh_distortion/isotropic_svd_energy_model_3d.cc', ...
    'cpp/energy_model/distortion_kernel/arap_kernel_2d.cc', ...
    'cpp/energy_model/distortion_kernel/flip_penalty_kernel_2d.cc',...
    'cpp/energy_model/distortion_kernel/sym_dirichlet_filtered_kernel_2d.cc',...
    'cpp/energy_model/distortion_kernel/arap_kernel_3d.cc', ...
    'cpp/energy_model/distortion_kernel/flip_penalty_kernel_3d.cc',...
    'cpp/energy_model/distortion_kernel/sym_dirichlet_filtered_kernel_3d.cc',...
    'cpp/common/util/linalg_util.cc', 'cpp/common/solver/eigen/eigen_solver.cc', ...
    'cpp/data_io/data_io_utils.cpp');

%%  compile 2D ABCD solver for all iterations  with Eigen
% Do not set _USE_PARDISO macro in linear_solver.h while compiling it
if ~compile_with_pardiso
    mex( '-DMEX_COMPILE_FLAG',['COMPFLAGS="$COMPFLAGS ' compiler_option '"'],['-I',eigen_path],['-I',boost_path],...
        ['-I',inc_path],['-I',VS_path],'ABCD_FixerOptimizer_2d_mex.cc', ...
        ['-I',VS_path],'ABCD_optimization_core_2d.cpp', ...
        'cpp/energy_model/mesh_distortion/isotropic_svd_energy_model_2d.cc', ...
        'cpp/energy_model/mesh_distortion/isotropic_svd_energy_model_3d.cc', ...
        'cpp/energy_model/distortion_kernel/arap_kernel_2d.cc', ...
        'cpp/energy_model/distortion_kernel/flip_penalty_kernel_2d.cc',...
        'cpp/energy_model/distortion_kernel/sym_dirichlet_filtered_kernel_2d.cc',...
        'cpp/common/util/linalg_util.cc', 'cpp/common/solver/eigen/eigen_solver.cc', ...
        'cpp/common/optimization/line_search_util.cc', 'cpp/common/optimization/stop_check_util.cc',...
        'cpp/data_io/data_io_utils.cpp','cpp/common/util/graph_util.cpp');
    
    %%  compile ABCD 3D code with Eigen
    % Do not set _USE_PARDISO macro in linear_solver.h while compiling it
    mex( '-DMEX_COMPILE_FLAG',['COMPFLAGS="$COMPFLAGS ' compiler_option '"'],['-I',eigen_path],['-I',boost_path],...
        ['-I',inc_path],['-I',VS_path],'ABCD_FixerOptimizer_3d_mex.cc', ...
        ['-I',VS_path],'ABCD_optimization_core_3d.cpp', ...
        'cpp/energy_model/mesh_distortion/isotropic_svd_energy_model_2d.cc', ...
        'cpp/energy_model/mesh_distortion/isotropic_svd_energy_model_3d.cc', ...
        'cpp/energy_model/distortion_kernel/arap_kernel_3d.cc', ...
        'cpp/energy_model/distortion_kernel/flip_penalty_kernel_3d.cc',...
        'cpp/energy_model/distortion_kernel/sym_dirichlet_filtered_kernel_3d.cc',...
        'cpp/common/util/linalg_util.cc', 'cpp/common/solver/eigen/eigen_solver.cc', ...
        'cpp/common/optimization/line_search_util.cc', 'cpp/common/optimization/stop_check_util.cc',...
        'cpp/data_io/data_io_utils.cpp','cpp/common/util/graph_util.cpp');
    
    disp('Mex compiled with Eigen');
else
    %% compile 2D ABCD  with Pardiso (Optional)
    pardiso_path = './';
    mex( '-DMEX_COMPILE_FLAG',['COMPFLAGS="$COMPFLAGS ' compiler_option '"'],['-I',eigen_path],['-I',boost_path],...
        ['-I',inc_path],['-I',VS_path],'ABCD_FixerOptimizer_2d_mex.cc', ...
        ['-I',VS_path], ['-L' pardiso_path], ...
        'ABCD_optimization_core_2d.cpp', ...
        'cpp/energy_model/mesh_distortion/isotropic_svd_energy_model_2d.cc', ...
        'cpp/energy_model/mesh_distortion/isotropic_svd_energy_model_3d.cc', ...
        'cpp/energy_model/distortion_kernel/arap_kernel_2d.cc', ...
        'cpp/energy_model/distortion_kernel/flip_penalty_kernel_2d.cc',...
        'cpp/energy_model/distortion_kernel/sym_dirichlet_filtered_kernel_2d.cc',...
        'cpp/common/util/linalg_util.cc', 'cpp/common/solver/eigen/eigen_solver.cc', ...
        'cpp/common/solver/pardiso/pardiso_solver.cc', ...
        'cpp/common/optimization/line_search_util.cc', 'cpp/common/optimization/stop_check_util.cc',...
        'cpp/data_io/data_io_utils.cpp','cpp/common/util/graph_util.cpp');
    
    %%  ABCD 3D code  with Pardiso (Optional)
    % Set "#define _USE_PARDISO 1" in  linear_solver.h
    % Put pardiso binaries in /mexed_solver/mex/, and link it with  mex
    pardiso_path = './';
    mex( '-DMEX_COMPILE_FLAG',['COMPFLAGS="$COMPFLAGS ' compiler_option '"'],['-I',eigen_path],['-I',boost_path],...
        ['-I',inc_path],['-I',VS_path], ['-L' pardiso_path], ...
        'ABCD_FixerOptimizer_3d_mex.cc', ...
        ['-I',VS_path],'ABCD_optimization_core_3d.cpp', ...
        'cpp/energy_model/mesh_distortion/isotropic_svd_energy_model_2d.cc', ...
        'cpp/energy_model/mesh_distortion/isotropic_svd_energy_model_3d.cc', ...
        'cpp/energy_model/distortion_kernel/arap_kernel_3d.cc', ...
        'cpp/energy_model/distortion_kernel/flip_penalty_kernel_3d.cc',...
        'cpp/energy_model/distortion_kernel/sym_dirichlet_filtered_kernel_3d.cc',...
        'cpp/common/util/linalg_util.cc', 'cpp/common/solver/eigen/eigen_solver.cc', ...
        'cpp/common/solver/pardiso/pardiso_solver.cc', ...
        'cpp/common/optimization/line_search_util.cc', 'cpp/common/optimization/stop_check_util.cc',...
        'cpp/data_io/data_io_utils.cpp','cpp/common/util/graph_util.cpp');
    
    disp('Mex compiled with Pardiso');
end